[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Roboracer Assets"
author = "Roboracers Project Developers"
maintainer = "Roboracers Project Developers"
description= "Isaac Lab for Roboracers"
keywords = ["extension", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "roboracer_assets"